# Generated by Django 4.2.2 on 2023-07-04 01:38

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True, validators=[app.models.validad_fecha])),
                ('numero_ventas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('costos', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingresos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
